#!/bin/bash

#IMPORTS
#NONE YET

#COMMAND
clear

#COLORS
#RED = \e[1;31m
#BLUE = \e[34m
#END = \e[0m

#COLORS2
red='\e[1;31m'
yellow='\e[0;33m'
Blue='\e[1;34m'

# ROOT
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   echo "Your not rooted, please root your Terminal."
   exit 1
fi

function banner
    {
      echo "
                        ____ _               _   ____
                       / ___| |__   ___  ___| |_|  _ \ ___  ___ ___  _ __
                      | |  _| '_ \ / _ \/ __| __| |_) / _ \/ __/ _ \| '_ \.
           /\.        | |_| | | | | (_) \__ \ |_|  _ <  __/ (_| (_) | | | |
          /**\.        \____|_| |_|\___/|___/\__|_| \_\___|\___\___/|_| |_|
         /****\   /\.             DEVELOPER: MZZGAMER | VERSION: V.1.0
        /      \ /**\.
       /  /\    /    \        /\    /\  /\      /\            /\/\/\  /\.
      /  /  \  /      \      /  \/\/  \/  \  /\/  \/\  /\  /\/ / /  \/  \.
     /  /    \/ /\     \    /    \ \  /    \/ /   /  \/  \/  \  /    \   \.
     /  /      \/  \/\   \  /      \    /   /    \.
     __/__/_______/___/__\___\__________________________________________________."
        echo -e "\e[1;31m                           !!!  TYPE -h TO SEE COMMANDS  !!!\e[0m"
        echo -e "\e[1;31m                           !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  \e[0m"
        echo ""
        echo ""
        echo ""
   }
banner

function help
    {
      echo "
  USAGE: run [core_commands], <sub_commands>
  example: run domain_scanner, | clear
  You get the point.

      ABOUT:
        GhostRecon is compact OSINT tool for OSINT investigators.
        Developer: mZzgamerDEV
        Status: Still under developement.

      SUBCOMMANDS:
        List of available commands that can be invoked using GhostRecon.

      <core_commands>

             domain_scanner           Search all possible information for Domains.
             IP_scanner               Search all possible information from an IP Address.
             phone_scanner            Search all possible information from a phone number.
             email_scanner            Search all possible information from an email.
             vuln_scanner             Search all possible Vulnerabilities.
             link_scanner             Sniff all links from a Domain.
             media_scanner            Search all possible social media accounts from a username.
             bitcoin_scanner          Search all bitcoin wallets addresses from target.


        <sub_commands>
          clear               Clear terminal
          update              Update tool
          banner              To spawn banner

   ABOUT ARGUMENTS:
     Showing additional information about this program.

      -h, --help            shows this help and exists.
      -v  --version         shows the version of the program and exists.

   Use 'run <core_command>' to learn more about each command. You can contact me
   if there is any issues by Twitter & Discord. (Discord) mZzgamer#8652 (Twitter) @mZzgamerDEV

   (CTRL+C to exit)"
      echo ""
      echo ""
    }

a1='clear' ##
a2='banner' ##
a3='update' ##
b1='run -v' ##
b2='-h' ##
b3='--help' ##
b4='run --version' ##
b5='run domain_scanner' #
b6='run IP_scanner' #
b7='run phone_scanner'
b8='run email_scanner'
b9='run vuln_scanner'
b10='run link_scanner'
b11='run media_scanner'
b12='run bitcoin_scanner'

#NEW COMMANDS
while true; do
  read -p " [GRECON] > " x
     if [ "$x" == "$a1" ]; then
         clear
     fi
     if [ "$x" == "$a2" ]; then
         banner
     fi
     if [ "$x" == "$a3" ]; then
         echo ""
         echo "-------------------------------------------------------------------------------------------------------------"
         echo -e "\e[1;31m  UPDATE IS STILL UNDER DEVELOPEMENT... AND THERE IS NO UPDATES!\e[0m"
         echo "-------------------------------------------------------------------------------------------------------------"
         echo ""
       fi
############################################################################################################
     if [ "$x" == "$b1" ]; then
         echo ""
         echo "-------------------------------------------------------------------------------------------------------------"
         echo -e "\e[1;31m  VERSION: V.1.0\e[0m"
         echo "-------------------------------------------------------------------------------------------------------------"
         echo ""
     fi
     if [ "$x" == "$b2" ]; then
         help
     fi
     if [ "$x" == "$b3" ]; then
         help
     fi
     if [ "$x" == "$b4" ]; then
       echo ""
       echo "-------------------------------------------------------------------------------------------------------------"
       echo -e "\e[1;31m  VERSION: V.1.0\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
     fi
     if [ "$x" == "$b5" ]; then
         echo ""
         echo -e "\e[1;31m!!!!!!!!!!!!!!!!!!!!!!!\e[0m"
         echo -e "\e[1;31m!!!  WIFI REQUIRED  !!!\e[0m"
         echo -e "\e[1;31m!!!!!!!!!!!!!!!!!!!!!!!\e[0m"
         echo ""
         echo "Example: kali.org (JUST ONE DOMAIN)"
         read -p "[DOMAIN]: " domain
         echo ""
         echo "Gathering Informations...."
         echo ""
         echo -e "\e[1;31m [*] ADMIN INFO (WHOIS INFO)\e[0m"
         echo "-------------------------------------------------------------------------------------------------------------"
         echo ""
         whois $domain
         echo ""
         echo -e "\e[1;31m [*] HOSTS AND IP ADDRESSES\e[0m"
         echo "-------------------------------------------------------------------------------------------------------------"
         echo ""
         cd
         cd spiderfoot/
         python3 ./sf.py -m sfp_dnsbrute,sfp_dnsresolve -s $domain -q
         echo ""
         echo ""
         echo ""
         echo -e "\e[1;31m [*] NAMES AND EMAILS\e[0m"
         echo "-------------------------------------------------------------------------------------------------------------"
         echo ""
         cd
         cd spiderfoot/
         python3 ./sf.py -m sfp_spider,sfp_names,sfp_email,sfp_phone -s $domain -q -F HUMAN_NAME,EMAILADDR,PHONENUMBER
         echo ""
         echo -e "\e[1;31m [*] DNS INFO\e[0m"
         echo "-------------------------------------------------------------------------------------------------------------"
         python3 ./sf.py -m sfp_dnsbrute,sfp_dnsresolve,sfp_portscan_tcp -s $domain -q -r
         echo ""
         echo -e "\e[1;31m [*] VULNERABILITIES\e[0m"
         echo "-------------------------------------------------------------------------------------------------------------"
         echo ""
         msfconsole -q -x "nmap -v --script vuln $domain ;exit ;"
         echo ""
         echo -e "\e[1;31m [*] LINKS SCANNED\e[0m"
         echo "-------------------------------------------------------------------------------------------------------------"
         echo ""
         curl https://api.hackertarget.com/pagelinks/?q=$domain
         echo ""
         echo "-------------------------------------------------------------------------------------------------------------"
         echo ""
         echo -e "\e[1;31m [*] DONE\e[0m"
         echo ""
     fi
     if [ "$x" == "$b6" ]; then
       echo ""
       echo -e "\e[1;31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\e[0m"
       echo -e "\e[1;31m!!!  WIFI AND SHODAN KEY REQUIRED  !!!\e[0m"
       echo -e "\e[1;31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\e[0m"
       echo ""
       read -p "[IP ADDRESS]: " ipaddress
       echo ""
       echo "Gathering Informations...."
       echo ""
       echo -e "\e[1;31m [*] IP LOCATION\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       trace -t $ipaddress
       echo ""
       echo -e "\e[1;31m [*] ADMIN INFO\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       whois $ipaddress
       echo ""
       echo -e "\e[1;31m [*] VULNERABILITIES\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       nmap -sS $ipaddress -O
       echo ""
       echo -e "\e[1;31m [*] SHODAN RESULTS\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       shodan stats --facets vuln net:$ipaddress
       echo ""
       shodan host $ipaddress
       echo ""
       echo -e "\e[1;31m [*] DNS RECORDS\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       curl http://api.hackertarget.com/reverseiplookup/?q=$ipaddress
       echo ""
       echo ""
       echo -e "\e[1;31m [*] DONE\e[0m"
       echo ""
     fi
     if [ "$x" == "$b7" ]; then
       echo ""
       echo "Please Enter The Number Followed By The Dialing Code"
       echo "for example : +447410490080 / +44 Is My Dialing Code"
       read -p "Phone Number: " phone_info
       echo ""
       echo "Gathering Information..."
       echo ""
       echo -e "\e[1;31m [*] PHONE $phone_info\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       cd
       cd Phone_locator/
       python Phone_locator.py $phone_info
       echo ""
       echo ""
     fi
     if [ "$x" == "$b8" ]; then
       echo ""
       read -p "Email Address: " email_info
       echo ""
       echo "Gathering Information..."
       echo ""
       echo -e "\e[1;31m [*] EMAIL $email_info\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       mailfy -m $email_info -p all
       echo ""
       echo ""
     fi
     if [ "$x" == "$b9" ]; then
       echo ""
       read -p "IP/DOMAIN: " vuln
       echo ""
       echo " Gathering Information..."
       echo ""
       echo -e "\e[1;31m [*] VULNERABILITY SCAN (METASPLOIT)\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       msfconsole -q -x "nmap -v --script vuln $vuln ;exit ;"
       echo ""
       echo -e "\e[1;31m [*] NMAP SCAN\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       nmap -sS $vuln -O
       echo ""
       echo -e "\e[1;31m [*] EXTRA VULNERABILITY SCAN\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
       cd
       cd spiderfoot/
       python3 ./sf.py -m sfp_dnsbrute,sfp_dnsresolve,sfp_portscan_tcp -s $vuln -q -r
       echo ""
     fi
     if [ "$x" == "$b10" ]; then
       echo ""
       read -p "Enter DOMAIN: " link
       echo ""
       echo "Gathering Information..."
       echo ""
       echo -e "\e[1;31m [*] SNIFFING LINKS\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       curl https://api.hackertarget.com/pagelinks/?q=$link
       echo ""
     fi
     if [ "$x" == "$b11" ]; then
       echo ""
       echo -e "\e[1;31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\e[0m"
       echo -e "\e[1;31m!!!  PUT IN POSSIBLE USERNAME  !!!\e[0m"
       echo -e "\e[1;31m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\e[0m"
       echo ""
       read -p "Username: " username
       echo ""
       echo "Gathering Information..."
       echo ""
       echo -e "\e[1;31m [*] POSSIBLE SOCIAL MEDIA ACCOUNTS\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       cd
       cd spiderfoot/
       python3 ./sf.py -m sfp_accounts -s $username -q
       echo ""
     fi
     if [ "$x" == "$b12" ]; then
       echo ""
       echo -e "\e[1;31m!!!!!!!!!!!!!!!!!!!!!!!\e[0m"
       echo -e "\e[1;31m!!!  PUT IN TARGET  !!!\e[0m"
       echo -e "\e[1;31m!!!!!!!!!!!!!!!!!!!!!!!\e[0m"
       echo ""
       echo "TARGET EXAMPLE - bitcoinforcharity.com"
       read -p "Target: " bitcoin
       echo ""
       echo "Gathering Information..."
       echo ""
       echo -e "\e[1;31m [*] BITCOIN WALLET ADDRESSES\e[0m"
       echo "-------------------------------------------------------------------------------------------------------------"
       cd
       cd spiderfoot/
       python3 ./sf.py -m sfp_spider,sfp_bitcoin -s $bitcoin -F BITCOIN_ADDRESS -q
       echo "-------------------------------------------------------------------------------------------------------------"
       python3 ./sf.py -m sfp_spider,sfp_ethereum -s $bitcoin -F ETHEREUM_ADDRESS -q
       echo "-------------------------------------------------------------------------------------------------------------"
       python3 ./sf.py -m sfp_spider,sfp_bitcoin,sfp_blockchain -s $bitcoin -F BITCOIN_ADDRESS,BITCOIN_BALANCE -q
       echo "-------------------------------------------------------------------------------------------------------------"
       echo ""
     fi
done

#    MODULES

#    whois $whois
#    curl http://api.hackertarget.com/geoip/?q=$geoip
#    curl http://api.hackertarget.com/reverseiplookup/?q=$ip_lookup
#    curl http://api.hackertarget.com/dnslookup/?q=$DNS_LOOKUP
#    curl https://api.hackertarget.com/reversedns/?q=$reversedns
#    curl https://api.telnyx.com/anonymous/v2/number_lookup/$phone_info
#    curl https://api.hackertarget.com/bannerlookup/?q=$grab_banner
#    curl http://api.hackertarget.com/nmap/?q=$nmap_scan
#    sshscan.py -t $sshscan
#    sqlmap -u $sqlhost2  searchgetby_id.$phphtml1?id=4 --dbs --columns -D scanme --tamper=space2comment --level 5
#    msfconsole -q -x "nmap -v --script vuln $vuln_scan ;exit ;"
#    osrf alias_generator
#    mailfy -m $email_info -p all
#    osrf alias_generator
#    curl https://api.hackertarget.com/pagelinks/?q=$link_sniffer
